### PR TITLE
add contact_group resource to the provider

### PR DESCRIPTION
**Pull request by gaalexandre**

### CODE REVIEW

**Comment by plumcraft** [comment]
Hello,

What is current status of these awesome features ? Looking forward to use contact group and ssl test features.

Let me know if i can help too.

Thanks

**Comment by marceloalmeida** [comment]
Is there any expectation when this will be merged to master?

**Comment by avivek** [comment]
This is something even we are looking at which enables full automation

**Comment by StupidScience** [comment]
Any reason why is it not merged yet? Or maybe any ETA here? We need this feature as well

**Pull request closed without merging**
