### PR TITLE
Set default status codes to what StatusCake sets them to

### PR DESCRIPTION
**Pull request by nh2**
Extracted from https://github.com/terraform-providers/terraform-provider-statuscake/pull/37#issuecomment-504247118

### CODE REVIEW

**Comment by nh2** [comment]
There may be one problem with this in general: These are HTTP status codes.

So they may not make sense for non-HTTP tests (like PING tests), in which StatusCake may not have this default.

I think the PR still makes sense because actually implements what's in the documentation so far and it's annoying for the user to have to manually set up this long list for each HTTP test. But perhaps afterwards we want to improve the defaults in general based on the test types afterwards?

**Comment by matschaffer** [comment]
@nh2 seems like we should hold on merge until we at least ensure it doesn't break ping tests entirely. Have you tried it?

And would you prefer we hold 1.0.0 until this PR is worked out?

**Comment by matschaffer** [comment]
Also curious what this will do when applied to tests created in TF w/o a statuscode list

**Comment by nh2** [comment]
> And would you prefer we hold 1.0.0 until this PR is worked out?

No, it can be done later; I'm currently running from my fork and don't use ping tests big-time (for where I do, I just manually overrode it to the emty list of status codes).

Probably better to test that change properly and release a follow-up version than to squeeze it in untested.

> Also curious what this will do when applied to tests created in TF w/o a statuscode list on the current 0.2.0 release.

I suspect it will show a diff in `terraform plan` and add them. But I'm not sure if tests with empty status codes even work. Do you have some currently where no status codes are shown in the StatusCake UI, and do they work?

**Comment by matschaffer** [comment]
Yeah, it looks like most of ours don't and they work as expected

**Comment by kennyheaton** [comment]
I'm sorry, I just opened a issue on this and didn't see there was already a merge request. I'm not sure the best idea is to hard code a default list. The API set's those defaults if you don't pass in StatusCode as a parameter. If their list ever changes the providers defaults and StatusCake's defaults will be different.

The statuscake Go client has the ability to omit empty attributes. Can I suggest that might be a better change?

**Comment by kennyheaton** [comment]
I opened pull request DreamItGetIT/statuscake#45 to address this.

**Comment by G-Rath** [comment]
@thde is this something you'd be interested in landing on your fork?

Your seems to be a lot less buggy than what's here (i.e I can actually set contact groups, delete tests, etc) but right now I'm getting a perceptual diff on `status_codes` that causes Terraform to error when attempting to apply due to no change occuring:

```
esource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # statuscake_test.test_site will be updated in-place
  ~ resource "statuscake_test" "test_site" {
        check_rate       = 30
        confirmations    = 0
        contact_group    = [
            "153159",
        ]
        do_not_find      = false
        enable_ssl_alert = false
        follow_redirect  = false
        id               = "5905247"
        node_locations   = []
        paused           = false
        port             = 0
        status           = "Down"
      - status_codes     = "204,205,206,303,400,401,403,404,405,406,408,410,413,444,429,494,495,496,499,500,501,502,503,504,505,506,507,508,509,510,511,521,522,523,524,520,598" -> null
        test_id          = "5905247"
        test_tags        = []
        test_type        = "HTTP"
        timeout          = 40
        trigger_rate     = 5
        uptime           = 0
        use_jar          = 0
        website_name     = "mywebsite"
        website_url      = "website.com/health"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

statuscake_test.test_site: Modifying... [id=5905247]

Error: Error Updating StatusCake Test: No data has been updated (is any data different?)

  on main.tf line 32, in resource "statuscake_test" "test_site":
  32: resource "statuscake_test" "test_site" {
```

I'm happy to help with this (+ general maintenance) where I can, but don't have the bandwidth or go skills to maintain a whole TF provider by myself at this point 😅

**Comment by thde** [comment]
@G-Rath I'm happy to merge a PR with tests :).

**Comment by G-Rath** [comment]
Have made a PR https://github.com/thde/terraform-provider-statuscake/pull/17

**Pull request closed without merging**
