### PR TITLE
Append v2 to package name and references

### LINKED ISSUE #75: Unable to reference v2 as a package
**Describe the bug**
When trying to use the latest release as a package the following error occurs: 
`require github.com/StatusCakeDev/terraform-provider-statuscake: version "v2.0.2-pre" invalid: should be v0 or v1, not v2`

**To Reproduce**
`require github.com/StatusCakeDev/terraform-provider-statuscake v2.0.2-pre`
`go mod tidy`

**Expected behavior**
Successfully required!

**Desktop (please complete the following information):**
 - OS: Mac

Pull request forthcoming 😄

### PR DESCRIPTION
**Pull request by EwanNoble**
To resolve #75

### CODE REVIEW

**Comment by tomasbasham** [comment]
Thanks for this. We had not considered this being used as a package. Out of curiosity how are you planning to use this?

**Comment by EwanNoble** [comment]
Hi @tomasbasham! I am exploring the possibility of consuming this in Pulumi via https://github.com/pulumi/pulumi-tf-provider-boilerplate
Alternatively it could be something Statuscake wishes to offer themselves 🚀 https://www.pulumi.com/registry/

**Comment by tomasbasham** [comment]
It's dawned on me today that even with this change you will not be able to make use of the code in this module because it all sits within the `internal` package. This was a deliberate decision we made since the code within was never intended to be used outside of this module. This is also how HashiCorp tend to implement their own providers.

**Review by tomasbasham — APPROVED** [review]

**Comment by tomasbasham** [comment]
Closing in favour of #101 which includes this commit but also includes the same change to other files.

**Pull request closed without merging**
